version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi
    command: bash .sh
    volumes:
      - .:/usr/src/
    ports:
      - "8000:8000"

#    environment:
#      -
    depends_on:
      - db
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}