# Generated by Django 3.2.13 on 2022-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hash_content', models.CharField(max_length=255, unique=True)),
                ('content', models.FileField(max_length=30, upload_to='file/<django.db.models.query_utils.DeferredAttribute object at 0x7fc901e35300>/%Y/%m/%d/%H%M%S')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ('created',),
            },
        ),
    ]
