# Generated by Django 3.2.13 on 2022-04-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_alter_filestorage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='content',
            field=models.FileField(upload_to='file/'),
        ),
    ]
