# Generated by Django 3.2.13 on 2022-04-20 12:28

from django.db import migrations, models
import file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_alter_filestorage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='content',
            field=models.FileField(upload_to=file.models.user_directory_path),
        ),
    ]
