version: "3.8"

services:
    filestorage:
        build: .
        container_name: filestorage
        command: bash .sh

        volumes:
            - .:/usr/src/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        env_file: .env
        volumes:
            - pgdata:/var/lib/postgresql/data11/

volumes:
    pgdata: